<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Stocks.fsx" />
    <Compile Include="StocksAsync.fsx" />
    <Compile Include="StockAnalyzer.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Collections.ParallelSeq" Version="1.2.0" />
    <PackageReference Include="XPlot.Plotly" Version="4.1.0" />
  </ItemGroup>

</Project>
